#!/bin/bash

## by José Paulo - https://github.com/JPAlvim

Host_Name=HOSTNAME

sudo scutil --set HostName $Host_Name
sudo scutil --set LocalHostName $Host_Name
sudo scutil --set ComputerName $Host_Name
dscacheutil -flushcache
