#!/bin/bash

## by José Paulo - https://github.com/JPAlvim

oldpass =
newpass =
user =

expect -c "
log_user 0
spawn sudo dscl . -passwd /Users/$user $oldpass
expect \"Permission denied. Please enter user's old password:\"
send "$newpass"\r
log_user 1
expect eof
"
