#!/bin/sh

# Modify the password string to match the desired firmware password.

password=default

expect -c "
log_user 0
spawn sudo firmwarepasswd -setpasswd
expect \"Setting Firmware Password\"
expect \"Enter new password:\"
send "${password}"\r
expect \"Re-enter new password:\"
send "${password}"\r
expect \"Password changed\"
spawn echo Password Changed\r
log_user 1
expect eof
"

title="Restart"
description="A security update has been pushed to your computer. Please, restart"
acceptText="Okay!"
closeText="No, thanks."

# Time before the notification times out, in seconds
timeOut="600"

# This if statement should not need to be changed. It simply uses the variables
#   above.
if /Library/Addigy/macmanage/MacManage.app/Contents/MacOS/MacManage action=notify title="${title}" description="${description}" closeLabel="${closeText}" acceptLabel="${acceptText}" timeout="$timeOut"; then
    # These commands can be changed to detemine what happens when the user
    #   clicks the "Accept" label.
    say "Accept label clicked"
    exit 0
else
    # These commands can be changed to detemine what happens when the user
    #   clicks the "Close" label.
    say "Close label clicked"
    exit 1
fi
