#!/bin/bash

## by José Paulo - https://github.com/JPAlvim

curUser=$(/usr/bin/stat -f%Su /dev/console)

TIMESTAMP=$(dscl . read /Users/$curUser | grep -A 1 passwordLastSetTime | grep -v passwordLastSetTime | awk '{print $1}' | sed 's/\..*$//' | sed 's/.*>//')
LastChangeDate=$(date -r $TIMESTAMP)
LastChangeYearDay=$(date -r $TIMESTAMP '+%j')
Today=$(date +%j)

DaysSince=$(expr $Today - $LastChangeYearDay)

echo "Username is: '$curUser'"
echo "Last Change Date: '$LastChangeYearDay'"
echo "Last Change Day of the Year: '$LastChangeDate'"
echo "Today in the Year: '$Today'"
echo "Days Since Last Change: '$DaysSince'"
