#!/bin/bash

# If you're changing an existing password, fill the variables as asked. If you're entering a firmware password for the first time, use only "new_password".
password=password_in_use

new_password=password_to_be

Firmware=$(sudo firmwarepasswd -check | grep "Password Enabled" | awk '{print $3}')

if [ "$Firmware" == "Yes" ];
  then
    expect -c "
      log_user 0
      spawn sudo firmwarepasswd -setpasswd
      expect \"Setting Firmware Password\"
      expect \"Enter new password:\"
      send "${password}"\r
      expect \"Re-enter new password:\"
      send "${password}"\r
      expect \"Password changed\"
      spawn echo 'Password Changed'
      spawn firmwarepasswd -check
      log_user 1
      expect eof
      "
    exit 0
  else

    expect -c "
      log_user 0
      spawn sudo firmwarepasswd -setpasswd
      expect \"Setting Firmware Password\"
      expect \"Enter new password:\"
      send "${new_password}"\r
      expect \"Re-enter new password:\"
      send "${new_password}"\r
      expect \"Password changed\"
      spawn echo 'Password Changed'
      spawn firmwarepasswd -check
      log_user 1
      expect eof
      "
    exit 0
fi
